Solution
mate-academy/react_clock pull request #1089
Opened 2022-11-20 18:04 UTC by Andriy-Shymkiv

[DEMO LINK](https://andriy-shymkiv.github.io/react_clock/)

2022-11-21 13:20 UTC, Artem66 approved these changes
as for me everything is fine

2022-11-21 15:41 UTC, denys-danyliuk requested changes

2022-11-21 15:41 UTC, denys-danyliuk commented on src/App.tsx
> +    });
move callback to method, watch this video from 5:05 to know why
https://mate.academy/learn/react/class-components#/video/3221

2022-11-21 15:41 UTC, denys-danyliuk commented on src/App.tsx
> +  }
you also need to unmount your event listeners

2022-11-22 07:05 UTC, Olexandr6 approved these changes
Good job 👍

2024-03-27 08:41 UTC, closed without merging