solution
mate-academy/react_clock pull request #1164
Opened 2022-12-29 17:05 UTC by batstolya

[DEMO LINK](https://batstolya.github.io/react_clock/)

2022-12-30 12:04 UTC, KrisPlanka approved these changes
looks good!)

2022-12-30 12:07 UTC, valerii-derkach requested changes
[let's add some styles](https://mateacademy.slack.com/archives/C048KMNGNKU/p1672225786792459)

2023-01-03 11:21 UTC, solaryasha approved these changes
👍

2023-01-03 11:21 UTC, solaryasha commented on src/App.tsx
> +import { Card, Icon, Image } from 'semantic-ui-react';
Semantic UI 👍

2026-07-13 23:08 UTC, closed without merging