clock
mate-academy/react_clock pull request #124
Opened 2021-01-15 13:50 UTC by Layrovell

[DEMO LINK](https://Layrovell.github.io/react_clock/)

2021-01-15 14:58 UTC, zhenya-mezhueva approved these changes

2021-01-16 09:06 UTC, aliceblunt8 requested changes

2021-01-16 09:06 UTC, aliceblunt8 commented on src/App.js
> +      The Clock was renamed from oddName to
```suggestion
      The Clock was renamed from oldName to
```

2021-01-16 09:06 UTC, aliceblunt8 commented on src/App.js
> +          : <p className="App_offer">cookies?</p>}
```suggestion
        {isClockVisible ? (
        <Clock name={this.state.clockName} />
        ) : (
        <p className="App_offer">cookies?</p>
        )}
```

2021-01-16 09:06 UTC, aliceblunt8 commented on src/Clock/Clock.jsx
> +  }
empty method? delete or use it

2021-01-16 09:06 UTC, aliceblunt8 commented on src/App.js
> +    clockName: '00:00:00',
```suggestion
    clockName: null,
```

2021-01-16 10:57 UTC, Layrovell commented on src/App.js
> +    clockName: '00:00:00',
https://prnt.sc/wtgqw3

2021-01-18 09:22 UTC, varseniuk requested changes

2021-01-18 09:22 UTC, varseniuk commented on src/App.js
> +          <p className="App_offer">cookies?</p>
```suggestion
          <p className="App__offer">cookies?</p>
```

2021-01-18 09:22 UTC, varseniuk commented on src/Clock/Clock.jsx
> +        }
```suggestion
        {name && (
            <div className="clock__title">
              The Clock was renamed from oldName to:
              <p className="clock__text">{`${name}`}</p>
            </div>
          )
        }
```

2021-01-18 16:16 UTC, varseniuk approved these changes

2023-04-05 21:31 UTC, closed without merging