Solution
mate-academy/react_clock pull request #1582
Opened 2023-06-09 12:31 UTC by Shevtsooov

[DEMO LINK](https://Shevtsooov.github.io/react_clock/)

2023-06-10 12:18 UTC, silchyn requested changes

2023-06-10 12:18 UTC, silchyn commented on src/App.tsx
> +  }
event listeners should also be removed

2023-06-10 12:18 UTC, silchyn commented on src/components/Clocks/Clock.tsx
> +          {this.props.clockName}
destructure `props`

2023-06-12 11:19 UTC, naziamoff approved these changes
looks good 👍

2023-06-12 11:19 UTC, naziamoff commented on src/App.tsx
> +  };
```suggestion
  handleRightClick = (e: MouseEvent) => {
    e.preventDefault();

    this.setState({ hasClock: false });
  };

  handleLeftClick = () => {
    this.setState({ hasClock: true });
  };
```

2024-05-05 10:48 UTC, closed without merging