add task solution
mate-academy/react_clock pull request #1696
Opened 2023-07-23 09:43 UTC by AndriiYelieva

[DEMO LINK](https://AndriiYelieva.github.io/react_clock/)

2023-07-23 10:02 UTC, VitaliyBodnar requested changes
- the tests are not passed
<img width="1200" alt="Screenshot 2023-07-23 at 13 01 59" src="https://github.com/mate-academy/react_clock/assets/64746943/4cb75e00-8a01-48ec-8d2d-bf652167d601">

2023-07-24 11:56 UTC, IvanFesenko requested changes
GJ. Check my comments

2023-07-24 11:56 UTC, IvanFesenko commented on src/App.tsx
> +    document.removeEventListener('contextmenu', this.hideClock);
Do not forget remove all added listeners - your forgot remove 'click'

2023-07-24 11:56 UTC, IvanFesenko commented on src/components/Clock.tsx
> +
```suggestion
        <span> time is </span>
```

2023-07-24 14:06 UTC, mykhalenych approved these changes

2024-09-12 11:00 UTC, closed without merging