implement clock mechanics
mate-academy/react_clock pull request #1787
Opened 2023-09-11 15:17 UTC by Koliras

[DEMO LINK](https://Koliras.github.io/react_clock/)

2023-09-11 16:12 UTC, FrontKid approved these changes
Good  job!

2023-09-13 12:59 UTC, roman-mirzoian requested changes
Good job, but there is quite a bit of work to be done.

2023-09-13 12:59 UTC, roman-mirzoian commented on src/components/Clock/Clock.tsx
> +    today: new Date(),
```suggestion
    currentDate: new Date(),
```

2023-09-13 12:59 UTC, roman-mirzoian commented on src/components/Clock/Clock.tsx
> +          {this.state.today.toUTCString().slice(-12, -4)}
You make similar calculations twice, so you should make a separate helper function for this.

2024-12-16 14:43 UTC, closed without merging