add Clock component with {name} props
mate-academy/react_clock pull request #1821
Opened 2023-09-13 11:47 UTC by neovendano

[DEMO LINK](https://neovendano.github.io/react_clock/)

2023-09-15 06:59 UTC, Moroz-Dmytro requested changes
Your clock is renaming too often

<img width="1745" alt="image" src="https://github.com/mate-academy/react_clock/assets/86789161/d3929378-4e47-4931-943b-34fa801ccd05">

2023-09-15 06:59 UTC, Moroz-Dmytro commented on src/App.tsx
> +        {this.state.hasClock && <Clock name={this.state.clockName} />}
Destructuring

2023-09-15 06:59 UTC, Moroz-Dmytro commented on src/components/Clock/Clock.tsx
> +      console.debug(`Renamed from ${prevProps.name} to ${this.props.name}`);
Destructuring

2023-09-15 08:34 UTC, neovendano commented
> Your clock is renaming too often
> 
> <img alt="image" width="1745" src="https://user-images.githubusercontent.com/86789161/268201337-d3929378-4e47-4931-943b-34fa801ccd05.png">

Sorry, it looks like older version of App. I forgot to 'npm run deploy'

2023-09-19 19:46 UTC, roman-mirzoian approved these changes
Well done 👍

2025-07-28 11:37 UTC, closed without merging