solution
mate-academy/react_clock pull request #21
Opened 2020-09-02 16:28 UTC by tykhan

[DEMO LINK](https://tykhan.github.io/react_clock/)

2020-09-02 16:42 UTC, artsashko approved these changes

2020-09-03 12:33 UTC, vkryvytskyy requested changes

2020-09-03 12:33 UTC, vkryvytskyy commented on src/App.js
> +  componentWillMount() {
<img width="594" alt="image" src="https://user-images.githubusercontent.com/38065883/92115162-b3a89c00-edfa-11ea-9db6-c97e48296896.png">

2020-09-03 12:33 UTC, vkryvytskyy commented on src/App.js
> +}
Create separate component <Clock /> and move all logic there

2020-09-03 15:39 UTC, vkryvytskyy approved these changes

2023-01-29 14:39 UTC, closed without merging