solution
mate-academy/react_clock pull request #314
Opened 2021-07-21 20:01 UTC by gponomarenko

[DEMO LINK](https://gponomarenko.github.io/react_clock/)

2021-07-22 04:51 UTC, yatania approved these changes
Good job)

2021-07-22 08:34 UTC, ArtemTopolskyi requested changes
![image](https://user-images.githubusercontent.com/57574816/126611109-a8ee3def-51a3-43ec-b812-a9b045f83c88.png)
Имя должно изменяться только при клике на кнопку, а не на каждый тик таймера

2021-07-22 10:25 UTC, gponomarenko commented
Оновив!

2021-07-23 07:32 UTC, ArtemTopolskyi approved these changes

2021-07-23 07:32 UTC, ArtemTopolskyi commented on src/App.js
> +            onClick={() => this.clockName()}
```suggestion
            onClick={this.clockName}
```

2021-07-23 07:32 UTC, ArtemTopolskyi commented on src/App.js
> +          {' '}
template string

2021-07-23 10:08 UTC, gponomarenko commented on src/App.js
> +          {' '}
Оновив

2023-11-06 14:49 UTC, closed without merging