React clock created
mate-academy/react_clock pull request #360
Opened 2021-09-03 12:23 UTC by Andrii-Pinchuk

2021-09-03 12:28 UTC, kristof22122 approved these changes
Good job!

2021-09-03 13:14 UTC, varseniuk requested changes
Let's split the logic between the components and change the logic a bit

2021-09-03 13:14 UTC, varseniuk commented on src/App.tsx
> +    setInterval(() => {
Let's create the component `Clock` and handle all about the time inside it.
Also, you should clear the interval when the component disappears from the page (componentWillUnmount)

2021-09-03 13:14 UTC, varseniuk commented on src/App.tsx
> +                  console.log(this.state.date)
This console.log should be inside setInterval

2021-09-03 13:14 UTC, varseniuk commented on src/App.tsx
> +          ? (
```suggestion
        {this.state.isClockVisible && (
```
Use this syntax of conditional rendering instead of ternaries

2021-09-06 13:13 UTC, Denchepornyuk approved these changes

2025-10-29 17:25 UTC, closed without merging