solution
mate-academy/react_clock pull request #363
Opened 2021-09-04 13:09 UTC by Vova-Stoliar

[DEMO LINK](https://Vova-Stoliar.github.io/react_clock/)

2021-09-06 05:58 UTC, dima-tkachenko commented on src/App.tsx
> +            {isClockVisible ? time : null}
Сюди потрібно передати клас Clock у якому і буде обчислюватися час.

2021-09-06 05:58 UTC, dima-tkachenko commented on src/App.tsx
> +    this.randomName = Math.floor(Math.random() * 100).toString();
не обов'язково тут робити строку. Це нічого не змінює

2021-09-07 08:53 UTC, Denchepornyuk requested changes

2021-09-07 08:53 UTC, Denchepornyuk commented on src/App.tsx
> +            onClick={() => this.setState({ clockName: Math.floor(Math.random() * 100).toString() })}
стрілочну функцію потрбіно винести за межі кнопки, записати її в окрему функцію і тут тільки звернутись до неї через this

2021-09-07 08:53 UTC, Denchepornyuk commented on src/Clock/Clock.tsx
> +  }
так не можна в componentDidUpdate не потрібно викликати componentDidMount, setInterval і так буде кожну секунду змінювати дату, ти його один раз запустив і далі він буде кожну секудну виконуватись

Через це в тебе в консолі зараз по два рази виводиться дата
<img width="185" alt="Screenshot 2021-09-07 at 11 45 33" src="https://user-images.githubusercontent.com/37452763/132314330-6685f5d0-a53a-46e6-b1b8-ce0cc3079cb8.png">

2021-09-07 08:53 UTC, Denchepornyuk commented on src/Clock/Clock.tsx
> +    }
це має бути в методі componentWillUnmount

2021-09-09 07:47 UTC, Denchepornyuk requested changes

2021-09-09 07:47 UTC, Denchepornyuk commented on src/App.tsx
> +            onClick={() => this.setName()}
```suggestion
            onClick={this.setName}
```

2021-09-09 07:47 UTC, Denchepornyuk commented on src/Clock/Clock.tsx
> +    this.setState({ time: new Date().toLocaleTimeString() });
цей setState тут не потрібний

2021-09-09 07:47 UTC, Denchepornyuk commented on src/Clock/Clock.tsx
> +      </>
для чого тут два React.Fragment

2021-09-09 08:18 UTC, Denchepornyuk approved these changes

2023-01-12 09:40 UTC, closed without merging