Done
mate-academy/react_clock pull request #58
Opened 2020-10-21 13:14 UTC by aionova

[DEMO LINK](https://aionova.github.io/react_clock/)

2020-10-21 13:21 UTC, yazheviks approved these changes
Класс!)

2020-10-22 13:33 UTC, aliceblunt8 requested changes

2020-10-22 13:33 UTC, aliceblunt8 commented on src/App.js
> +  toggleVisible = () => {
```suggestion
  toggleVisibility = () => {
```

2020-10-22 13:33 UTC, aliceblunt8 commented on src/components/Clock/Clock.js
> +  }
you also need to clear the timer when the Clock is removed from the DOM, cause now the clock is still ticking in the console event after the Clock component is destroyed
hint: use componentWillMount and clearInterval
https://reactjs.org/docs/state-and-lifecycle.html

2020-10-22 13:33 UTC, aliceblunt8 commented on src/components/Clock/Clock.js
> +      </div>
it's better to destructure state and props

2020-10-22 13:33 UTC, aliceblunt8 commented on src/components/Clock/Clock.js
> +  }
also, let's create a separate method for updating the time (we can call it 'tick')

2020-10-23 09:22 UTC, aliceblunt8 approved these changes

2023-09-27 08:14 UTC, closed without merging