sol
mate-academy/react_clock pull request #597
Opened 2022-02-16 17:47 UTC by maksym-mishchanchuk

[DEMO LINK](https://maksym-mishchanchuk.github.io/react_clock/)

2022-02-17 07:38 UTC, jursylian approved these changes
Good job!

2022-02-17 09:52 UTC, OleksiiBlezniuk requested changes

2022-02-17 09:52 UTC, OleksiiBlezniuk commented on src/App.tsx
> +            onClick={() => this.setState({ clockVisible: true })}
Вынеси в отдельный метод

2022-02-17 09:52 UTC, OleksiiBlezniuk commented on src/App.tsx
> +            onClick={() => this.setState({ clockVisible: false })}
Вынеси в отдельный метод

2022-02-17 09:52 UTC, OleksiiBlezniuk commented on src/App.tsx
> +            onClick={() => this.setState({ number: Math.floor(Math.random() * 10) })}
Вынеси в отдельный метод

2022-02-17 09:52 UTC, OleksiiBlezniuk commented on src/Clock.tsx
> +    date: '',
Из-за этого время появится только через секунду, добавь сразу время

2022-02-17 09:52 UTC, OleksiiBlezniuk commented on src/Clock.tsx
> +    this.state.timerId = setInterval(() => {
setState

2022-02-18 11:13 UTC, OleksiiBlezniuk requested changes

2022-02-18 11:13 UTC, OleksiiBlezniuk commented on src/App.tsx
> +            onClick={() => this.show()}
```suggestion
            onClick={this.show}
```

2022-02-18 11:13 UTC, OleksiiBlezniuk commented on src/App.tsx
> +            onClick={() => this.show()}
Ты же не передаёшь ничего в метод, обёртка не нужна, просто передай метод

2022-02-18 11:13 UTC, OleksiiBlezniuk commented on src/Clock.tsx
> +    });
А как теперь в state обновляется date?

2022-02-18 11:13 UTC, OleksiiBlezniuk commented on src/Clock.tsx
> +    });
```suggestion
    const timerId = setInterval(() => {
        this.setState({
          date: new Date().toLocaleTimeString(),
        })
        // eslint-disable-next-line no-console
        (console.log(new Date().toLocaleTimeString()));
      }, 1000);
    });

    this.setState({
      timerId,
    });
```

2022-02-18 11:26 UTC, maksym-mishchanchuk commented on src/App.tsx
> +            onClick={() => this.show()}
без стрілки і () - не працює

2022-02-18 11:39 UTC, OleksiiBlezniuk requested changes

2022-02-18 11:39 UTC, OleksiiBlezniuk commented on src/App.tsx
> +            onClick={() => this.show()}
Может ты забыл удалить () после метода?

2023-09-12 08:14 UTC, closed without merging