Develop
mate-academy/react_clock pull request #60
Opened 2020-10-21 14:24 UTC by AndriiManyak

[DEMO LINK](https://andriimanyak.github.io/react_clock/)

2020-10-22 17:49 UTC, OleksandrMykoliuk approved these changes

2020-10-23 09:36 UTC, aliceblunt8 requested changes
no need to move ALL proptypes to other files
(usually we move only proptypes connected with Proptypes.shapes, because they take too much space in every single file and we can reuse them in other components)
move all proptypes to the component's files

2020-10-23 09:36 UTC, aliceblunt8 commented on src/components/Clock/Clock.js
> +  }
you also need to clear the timer when the Clock is removed from the DOM, cause now the clock is still ticking in the console even after the Clock component is destroyed
hint: use componentWillMount and clearInterval
https://reactjs.org/docs/state-and-lifecycle.html

2020-10-23 09:36 UTC, aliceblunt8 commented on src/components/Clock/Clock.js
> +
use ternary operator instead of if-statement

2020-10-23 09:36 UTC, aliceblunt8 commented on src/components/shapes/ClockShape.js
> +}).isRequired;
```suggestion
export const ClockShape = {
  isVisible: PropTypes.bool.isRequired,
}
```

2020-10-23 09:36 UTC, aliceblunt8 commented on src/components/shapes/ButtonShape.js
> +}).isRequired;
```suggestion
export const ButtonShape = {
  handleClick: PropTypes.func.isRequired,
};
```

2020-10-23 09:36 UTC, aliceblunt8 commented on src/components/shapes/ButtonSetNameShape.js
> +}).isRequired;
```suggestion
export const ButtonSetNameShape = {
  handleClick: PropTypes.func.isRequired,
};
```

2020-10-26 09:11 UTC, Vladimir-Beliy requested changes

2020-10-26 09:11 UTC, Vladimir-Beliy commented on src/components/Button/Button.js
> +  <button type="button" onClick={handleClick}>
```suggestion
export const Button = ({ handleClick }) => (
  <button type="button" onClick={handleClick}>
```

2020-10-26 09:11 UTC, Vladimir-Beliy commented on src/components/Clock/Clock.js
> +      </>
```suggestion
        <span>{time.toLocaleTimeString()}</span>
```

2020-10-26 09:11 UTC, Vladimir-Beliy commented on src/components/Clock/Clock.js
> +  }
что ты тут делаешь?

2020-10-26 09:11 UTC, Vladimir-Beliy commented on src/App.js
> +          }
почему часы внутри параграфа?

2020-10-26 10:04 UTC, Vladimir-Beliy requested changes

2020-10-26 10:04 UTC, Vladimir-Beliy commented on src/App.js
> +          {' '}
почему текст внутри дива?

2020-10-26 10:04 UTC, Vladimir-Beliy commented on src/App.js
> +        </div>
```suggestion
          }
        </div>
```

2020-10-26 11:23 UTC, Vladimir-Beliy approved these changes

2026-02-12 23:09 UTC, closed without merging