Solution
mate-academy/react_clock pull request #644
Opened 2022-04-27 18:03 UTC by FocusHuK

2022-04-28 20:26 UTC, vkryvytskyy requested changes

2022-04-28 20:26 UTC, vkryvytskyy commented on README.md
> + [DEMO LINK](https://focushuk.github.io/react_clock/)
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/38065883/165839656-c0edb624-cb5c-40a3-a2e6-90397192a7be.png">
Тут не то что надо

Проверь что для билда gh-pages используется правильная ветка, как показано на видео

https://user-images.githubusercontent.com/38065883/144253618-cab69f76-2bad-470e-a1e4-153a08221108.mov

2022-05-09 16:12 UTC, FocusHuK commented on README.md
> + [DEMO LINK](https://focushuk.github.io/react_clock/)
![image](https://user-images.githubusercontent.com/82656141/167452165-b0e37753-058a-4048-a6e7-9a81f36e72ab.png)
https://focushuk.github.io/react_clock/

2022-05-09 16:12 UTC, FocusHuK commented on README.md
> + [DEMO LINK](https://focushuk.github.io/react_clock/)
сделал все как на видео, но все равно открывается другая страница. в чем еще может быть проблема?

2022-05-10 18:49 UTC, marina-tilniak commented on README.md
> + [DEMO LINK](https://focushuk.github.io/react_clock/)
передивися ще раз відео, там вибрана не гілка develop

2022-05-20 17:14 UTC, FocusHuK commented on README.md
> + [DEMO LINK](https://focushuk.github.io/react_clock/)
![image](https://user-images.githubusercontent.com/82656141/169579121-bf2a1043-5df4-4fc2-80dc-4b0539e9c0f2.png)
Выбрал другую ветку, ну все равно не работает

2022-07-18 16:11 UTC, closed without merging