Solution
mate-academy/react_clock pull request #692
Opened 2022-05-22 15:52 UTC by DariaVeretyak

https://dariaveretyak.github.io/react_clock/

2022-05-23 17:43 UTC, vkryvytskyy requested changes

2022-05-23 17:43 UTC, vkryvytskyy commented on README.md
> + [DEMO LINK](https://DariaVeretyak.github.io/react_clock/)
https://user-images.githubusercontent.com/38065883/169877020-aca4d4ca-40b9-4957-a25e-b0e1e6337bf2.mov

Одно и то же время не должно выводиться в консоль больше одного раза, даже когда я переименую часы

2022-05-30 11:14 UTC, Bohdan-Maksymiuk approved these changes
Good job 👍

2022-05-30 11:14 UTC, Bohdan-Maksymiuk commented on src/App.tsx
> +  ];
move this variable outside the component

2024-04-01 19:00 UTC, closed without merging