Solution
mate-academy/react_clock pull request #733
Opened 2022-06-07 06:00 UTC by PRO-GRAM-MER

[DEMO LINK](https://pro-gram-mer.github.io/react_clock/)

2022-06-07 16:39 UTC, LukaszGryziewicz approved these changes
Good job! 👍

2022-06-07 16:39 UTC, LukaszGryziewicz commented on src/App.scss
> +}
missing empty last line

2022-06-07 16:39 UTC, LukaszGryziewicz commented on src/App.tsx
> +          {this.state.isClockVisible
You could also use the destructed state here

2022-06-08 10:20 UTC, meforoma requested changes

2022-06-08 10:20 UTC, meforoma commented on src/App.tsx
> +    const { clockName } = this.state;
```suggestion
    const { clockName, isClockVisible } = this.state;
```

2022-06-08 10:20 UTC, meforoma commented on src/App.tsx
> +          {this.state.isClockVisible
upvote
```suggestion
          {isClockVisible
```

2022-06-08 10:20 UTC, meforoma commented on src/components/Clock.tsx
> +        </h3>
let's keep clock name not hidden
so that you hide the time counter, but name is visible
and we can change name while counter is hidden

2022-06-09 10:29 UTC, meforoma approved these changes

2026-03-29 20:35 UTC, closed without merging