solution
mate-academy/react_clock pull request #762
Opened 2022-07-08 11:53 UTC by Pavlo000

2022-07-10 11:07 UTC, illavodonis requested changes
Хороша робота, лишилось тільки дещо поправити

2022-07-10 11:07 UTC, illavodonis commented on src/components/Clock/Clock.tsx
> +  }, 1000);
Так само слід перенести в `componentDidMount`

2022-07-10 11:07 UTC, illavodonis commented on src/components/Clock/Clock.tsx
> +    console.log(this.state.date.toLocaleTimeString());
Це погане місце для `console.log` коли компонента через зміну назви рендериться даний рядок спрацьовує двічі  тобто :

- Коли змінився час
- Коли змінилась назва
![image](https://user-images.githubusercontent.com/34716282/178142232-1ab96bf7-df97-4349-bbf3-8243924efec8.png)

2022-07-11 11:11 UTC, illavodonis approved these changes
GJ :fire:

2022-07-11 14:51 UTC, mykola-koval approved these changes
<img width="301" alt="image" src="https://user-images.githubusercontent.com/90685701/178292315-92cc44ef-1673-405c-b74d-0bd52cf23e3f.png">
you can prevent context menu from opening

2024-11-26 18:25 UTC, closed without merging