first commit
mate-academy/react_clock pull request #803
Opened 2022-07-13 05:45 UTC by khrystyna-sabat

[DEMO LINK](https://khrystyna-sabat.github.io/react_clock/)

2022-07-13 20:41 UTC, yanaost approved these changes
GJ!

2022-07-14 05:51 UTC, Olexandr6 requested changes
You missed a task requirement:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52370890/178909525-792e19a1-6c09-4d13-ad3f-a1068bb1c65d.png">

2022-07-14 05:51 UTC, Olexandr6 commented on src/App.tsx
> +    });
You should remove event listeners and stop interval in `ComponentWillUnmount`, as well

2022-07-14 15:06 UTC, Olexandr6 approved these changes

2022-11-21 15:34 UTC, closed without merging