Solution
mate-academy/react_clock pull request #809
Opened 2022-07-15 12:45 UTC by ik-web

[DEMO LINK](https://ik-web.github.io/react_clock/)

2022-07-15 13:23 UTC, vsupruniuk requested changes

2022-07-15 13:23 UTC, vsupruniuk commented on src/components/Clock/Clock.tsx
> +  }, 1000);
Час потрібно друкувати також і в консолі

2022-07-16 09:36 UTC, vsupruniuk approved these changes
Nice👍

2022-07-18 07:40 UTC, illiarerun approved these changes
Approve, but pay attention to my comments:

2022-07-18 07:40 UTC, illiarerun commented on src/App.tsx
> +    }
you don't even use this handler
```suggestion
```

2022-07-18 07:40 UTC, illiarerun commented on src/components/Clock/Clock.tsx
> +  }, 1000);
you need to do it in `componentDidMount`

2022-07-18 09:23 UTC, ik-web commented on src/App.tsx
> +    }
Fixed

2022-09-14 13:43 UTC, closed without merging