React Clock
mate-academy/react_clock pull request #993
Opened 2022-10-14 13:17 UTC by Vladosik1337

[DEMO LINK](https://Vladosik1337.github.io/react_clock/)

2022-10-17 09:31 UTC, anastasiia-nahaiska approved these changes
Nice!))

2022-10-19 03:41 UTC, silchyn requested changes

2022-10-19 03:41 UTC, silchyn commented on src/App.tsx
> +  };
Names of functions violate the checklist, it should be called 'handle'

2022-10-19 03:41 UTC, silchyn commented on src/App.tsx
> +  }
Be careful to the task, this should be done in the Clock

2022-10-19 03:41 UTC, silchyn commented on src/App.tsx
> +            hasClock={this.state.hasClock}
We do not need to pass hasClock, Clock will not use it anyway (Clock will not render if it is false)

2022-10-19 03:41 UTC, silchyn commented on src/App.tsx
> +            clockName={this.state.clockName}
Destructure the state

2022-10-20 02:04 UTC, silchyn requested changes
You forgot to call `preventDefault` for the context menu event

2022-10-20 02:04 UTC, silchyn commented on src/App.tsx
> +        )}
```suggestion
        {hasClock && <Clock clockName={clockName} />}
```

2022-10-21 01:53 UTC, silchyn approved these changes
Cool!

2025-11-08 12:34 UTC, closed without merging